### ISSUE TITLE
folder_list.sh is not available

### ISSUE THREAD

**Issue by fprados** [sct-pipeline/spine_generic#13]
The first script to run is prepare_data.sh and it requires folder_list.sh, but the content of this file is not clear and the file is not available.

**Comment by jcohenadad** [comment]
The script `prepare_data.sh` should not be run according to the up-to-date [How to run the pipeline](https://github.com/sct-pipeline/spine_generic#how-to-run). However, I agree that this script needs documentation and better purpose. This is already addressed in the following issue: https://github.com/sct-pipeline/spine_generic/issues/12
